CXXFLAGS=-Wall -Werror -std=gnu++17 -fno-operator-names -ggdb -O0
LINK.o=$(LINK.cc) -v
03-self-improve-form: 03-self-improve-form.cpp
intellect: intellect.cpp
	g++ -ggdb -std=c++11 intellect.cpp  -Wl,--print-map
